apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  namespace: default
spec:
  volumes:
  - name: workdir
    emptyDir: {}
  initContainers:
  - name: install
    image: busybox
    command:
    - wget
    - -O
    - /work_dir/index.html
    - http://www.baidu.com
    volumeMounts:
    - name: workdir
      mountPath: /work_dir
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html